"""db creation

Revision ID: 818fe3d6a4ff
Revises: 
Create Date: 2024-08-23 21:33:51.468373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818fe3d6a4ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=80), nullable=False),
    sa.Column('game_link', sa.String(length=250), nullable=False),
    sa.Column('game_description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_description'),
    sa.UniqueConstraint('game_link'),
    sa.UniqueConstraint('game_name')
    )
    op.create_table('game_general_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_manufacture', sa.String(length=80), nullable=False),
    sa.Column('game_first_main_actor', sa.String(length=80), nullable=False),
    sa.Column('game_second_main_actor', sa.String(length=80), nullable=False),
    sa.Column('game_third_main_actor', sa.String(length=80), nullable=False),
    sa.Column('game_fourth_main_actor', sa.String(length=80), nullable=False),
    sa.Column('game_year_release', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_manufacture')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_general_info')
    op.drop_table('game')
    # ### end Alembic commands ###
